//User
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADMIN_UPDATE_USER = 'ADMIN_UPDATE_USER';
export const ADMIN_APPROVE_COURSE = "ADMIN_APPROVE_COURSE";
export const ADMIN_CANCEL_COURSE = "ADMIN_CANCEL_COURSE";
export const ADMIN_ADD_NEW_COURSE = "ADMIN_ADD_NEW_COURSE";
export const ADMIN_UPDATE_COURSE = "ADMIN_UPDATE_COURSE";
export const ADMIN_UPLOAD_IMAGE = "ADMIN_UPLOAD_IMAGE";

// List
export const LIST_COURSE_PENDING = "LIST_COURSE_PENDING";
export const LIST_COURSE_ACCEPTED = "LIST_COURSE_ACCEPTED";
export const LIST_USERS = "LIST_USERS";
export const LIST_CATEGORY = "LIST_CATEGORY";
export const LIST_COURSES = "LIST_COURSES";
export const LIST_USER_PENDING = "LIST_USER_PENDING";
export const LIST_COURSE_PAGINATION = "LIST_COURSE_PAGINATION";



