//User
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADMIN_UPDATE_USER = 'ADMIN_UPDATE_USER';
export const ADMIN_APPROVE_COURSE = "ADMIN_APPROVE_COURSE";

// List
export const LIST_COURSE_PENDING = "LIST_COURSE_PENDING";
export const LIST_COURSE_ACCEPTED = "LIST_COURSE_ACCEPTED";
export const LIST_USERS = "LIST_USERS";



